name: Build and publish the master docker-ckan image
on:
  schedule:
    - cron: "15 5 * * *"

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-docker-publish.yml
    with:
      ckan-major-version: "master"
      ckan-version: "master"
      base-tags: "ckan/ckan-base:master,ckan/ckan-base:master-py3.10"
      dev-tags: "ckan/ckan-dev:master,ckan/ckan-dev:master-py3.10"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
